name: Deploy to GitHub Pages via Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build with Docker
        run: |
          docker build -t my-app .
          docker create --name app-container my-app
          docker cp app-container:/usr/share/nginx/html ./dist
          docker rm app-container
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist